parameters:
#    site_front_end.example.class: Site\FrontEndBundle\Example

services:
#    site_front_end.example:
#        class: %site_front_end.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
